[project]
name = "ft_package"
version = "0.0.1"
authors = [{name = cgelgon}, {email = "cgelgon@42.fr"}]
licence = {file = "LICENSE"}
description = "A sample test package"
readme = "README.md"
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"